version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Install NPM dependencies
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - echo env var $ENV_NAME
      - sls deploy
  post_build:
    commands:
      - echo Deployment completed on `date`
